---
- name: sysvinit
  block:
    - name: sysvinit disable CTRL-ALT-DEL reboot keybinding
      lineinfile:
        dest: /etc/inittab
        regexp: '^ca{{":"}}.*{{":"}}ctrlaltdel.*'
        line: 'ca{{":"}}12345{{":"}}ctrlaltdel{{":"}}{{ ctrl_alt_del_sysvinit_disable_action }}'
        state: present
      when: ctrl_alt_del_state == "disable"

    - name: sysvinit enable CTRL-ALT-DEL reboot keybinding
      lineinfile:
        dest: /etc/inittab
        regexp: '^ca{{":"}}.*{{":"}}ctrlaltdel.*'
        line: 'ca{{":"}}12345{{":"}}ctrlaltdel{{":"}}{{ ctrl_alt_del_sysvinit_enable_action }}'
        state: present
      when: ctrl_alt_del_state == "enable"
  when: ansible_service_mgr == "sysvinit"


- name: systemd
  block:
    - name: systemd disable CTRL-ALT-DEL reboot keybinding
      systemd:
        name: "{{ ctrl_alt_del_systemd_unit }}"
        enabled: no
        masked: yes
        daemon_reload: yes
      when: ctrl_alt_del_state == "disable"

    - name: systemd enable CTRL-ALT-DEL reboot keybinding
      systemd:
        name: "{{ ctrl_alt_del_systemd_unit }}"
        enabled: yes
        masked: no
        daemon_reload: yes
      when: ctrl_alt_del_state == "enable"
  when: ansible_service_mgr == "systemd"
