---
- name: Sysvinit
  tags:
    - configure
    - sysvinit
  when: ansible_service_mgr == "sysvinit"
  block:
    - name: Sysvinit disable CTRL-ALT-DEL reboot keybinding
      become: true
      when:
        - ctrl_alt_del_state == "disable"
      ansible.builtin.lineinfile:
        dest: /etc/inittab
        regexp: '^ca{{ ":" }}.*{{ ":" }}ctrlaltdel.*'
        line: 'ca{{ ":" }}12345{{ ":" }}ctrlaltdel{{ ":" }}{{ ctrl_alt_del_sysvinit_disable_action }}'
        state: present

    - name: Sysvinit enable CTRL-ALT-DEL reboot keybinding
      become: true
      when:
        - ctrl_alt_del_state == "enable"
      ansible.builtin.lineinfile:
        dest: /etc/inittab
        regexp: '^ca{{ ":" }}.*{{ ":" }}ctrlaltdel.*'
        line: 'ca{{ ":" }}12345{{ ":" }}ctrlaltdel{{ ":" }}{{ ctrl_alt_del_sysvinit_enable_action }}'
        state: present


- name: Systemd
  tags:
    - configure
    - systemd
  when: ansible_service_mgr == "systemd"
  block:
    - name: Systemd disable CTRL-ALT-DEL reboot keybinding
      become: true
      when:
        - ctrl_alt_del_state == "disable"
      ansible.builtin.systemd:
        name: "{{ ctrl_alt_del_systemd_unit }}"
        enabled: false
        masked: true
        daemon_reload: true

    - name: Systemd enable CTRL-ALT-DEL reboot keybinding
      become: true
      when:
        - ctrl_alt_del_state == "enable"
      ansible.builtin.systemd:
        name: "{{ ctrl_alt_del_systemd_unit }}"
        enabled: true
        masked: false
        daemon_reload: true
